### ISSUE TITLE
Receiver value too small to hold result. 

### ISSUE THREAD

**Issue by jvalance** [NielsLiisberg/cvtrpgfree#1]
Hello Niels,
I am trying to use this utility, but I am getting an exception. It is because I have an RPG with over 10K lines of code, and there is an array index that is only 3,0 decimal (max 999). I encountered the same problem with the original version of this by Ewarwoowar. In that version, I was able to get around the problem by changing every 3 digit packed decimal variable to decimal 9,0. I was going to try same thing with your newer version, but I could not find the RPG source for CVTRPGFRER - it is missing from the QRPGLESRC file (the other SRC-PF each have members). I used the SAVF to install the programs on my system. 

Can you please either provide the RPG source, or fix the problem as I did by expanding the length of all the 3 digit variables? 

Please let me know when solution is available, with a message to my email: jvalance@profoundlogic.com.

Thank you for your work on this, and for addressing this issue. 

- John Valance

![image](https://user-images.githubusercontent.com/6464749/74121231-b7da4700-4b94-11ea-85cb-8d06bf0d472f.png)

![image](https://user-images.githubusercontent.com/6464749/74121449-988fe980-4b95-11ea-9f11-ba954fdf7301.png)

**Comment by NielsLiisberg** [comment]
Hi John,

Issue is fixed!! 

Note this is project is relying 100% git and stream files  so you will not find the typical QRPGLESRC  anywhere. The source is in the /src folder and you build the project with gmake all. 

It is easily build with my vsCode plugin for ILE RPGLE

<img width="1541" alt="vsCode and RPGLE" src="https://user-images.githubusercontent.com/2787230/74142701-ba22bc80-4bf9-11ea-9d7c-c9fe629edcf5.png">
 

Thank you for your feedback

**Comment by NielsLiisberg** [comment]
Hi John,

Issue is fixed!!

Note this is project is relying 100% git and stream files so you will not
find the typical QRPGLESRC anywhere. The source is in the /src folder and
you build the project with gmake all.

It is easily build with my vsCode plugin for ILE RPGLE

[image: vsCode and RPGLE]
<https://user-images.githubusercontent.com/2787230/74142701-ba22bc80-4bf9-11ea-9d7c-c9fe629edcf5.png>

Thank you for your feedback
